seed: 42
optimizer_class: Adam
learner_device: cpu
actor_device: cpu
weights_only: false
model_arch: conv_model
unexplored_action: 1.0e-05
worker_type: evaluate
noise_eps: 0.25
c_puct: 0.5
dirichlet_alpha: 0.3
temperature_tau: 0.0
n_blocks: 12
hidden_dim: 128
embedding_dim: 16
kernel_size: 3
normalize: false
rescale_value_input: false
rescale_se_input: false
obs_space_kwargs: {}
reward_space_kwargs: {}
act_space: BasicActionSpace
obs_space: HistoricalObs
reward_space: GameResultReward
search_threads: 1
max_processes: 1
simulation_num_per_move: 125
model_dir: models
best_model_weight_fname: mcts_phase4.pt
use_mixed_precision: true
discounting: 0.999
reduction: mean
load_dir: null
n_value_warmup_batches: 0