#defaults:
#- override hydra/job_logging: colorlog
#- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: conv_debug
## WANDB params
# The wandb project name
project: MCTS_Connect4
# The wandb user to log to
entity: filipinogambino
# The wandb group for the run
group: debug

weights_only: false
model_arch: conv_model

total_steps: 1000
c: .9
unexplored_action: 1e-5
disable_wandb: true
max_steps: 1000
n_rollouts: 1000
worker_type: self_play # self_play, optimize, evaluate
seed: 42
device: cpu
unroll_length: 16
batch_size: 16

virtual_loss: 3
noise_eps: .25
c_puct: 1.5
dirichlet_alpha: .3
tau_decay_rate: .99
n_blocks: 8
hidden_dim: 128
embedding_dim: 32
kernel_size: 3
normalize: false
rescale_value_input: false
rescale_se_input: false

obs_space_kwargs: {}
reward_space_kwargs: {}
act_space: BasicActionSpace
obs_space: HistoricalObs
reward_space: GameResultReward

optimizer_class: Adam
optimizer_kwargs:
  lr: 1e-5
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
min_lr_mod: .002

actor_device: cpu
learner_device: cpu

# Play
search_threads: 1
max_processes: 1
simulation_num_per_move: 7

# Play Data
nb_game_in_file: 100